bug:
  - "(?i)\\b(bug|error|exception|stack trace|crash|fails?)\\b"

enhancement:
  - "(?i)\\b(feature|enhancement|request|idea|improvement)\\b"

documentation:
  - "(?i)\\b(doc|docs|readme|documentation)\\b"

question:
  - "(?i)\\b(question|how do i|what is|why|help with)\\b"

frontend:
  - "(?i)\\b(ui|css|style|layout|javascript|client|frontend)\\b"

PHP:
  - "(?i)\\b(php|backend|server|api|mysql|query|session|auth)\\b"
