name: Release Drafter
on:
  push:
    branches: [ main ]        # <-- change to your default branch if not main
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        # no config-name: defaults to ".github/release-drafter.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
